### PR TITLE
Matrix plus is working, javatest isn't.

### PR DESCRIPTION
**Pull request by cambelem**
I'll fix the branch being behind master, however I'm having issues with the javatests if you could look at it. #27

### CODE REVIEW

**Comment by Cruisererick** [comment]
one thing in plus function m is not columns, m are rows. 
Parameters:
m - Number of rows.
n - Number of colums.

On the test i don't think you need to do the fail test because in the original method there is no exception throw meaning that they are letting that exception to be handle else where outside of the plus. 

public Matrix plus(Matrix B)
C = A + B
Parameters:
B - another matrix
Returns:
A + B

And finally the test will always fail because: matrix = matrix.plus(testMatrix);  matrix is fill with 2 and test is will with 4 giving 6 in the end, assertArrayEquals("Matrice are not the same dimensions.", matrix.matrix, testMatrix.matrix) so here you have 6 compare to 4 and exception will occur before the assert.

**Comment by cambelem** [comment]
I see, I'll change it and get it going.

**Comment by cambelem** [comment]
Need you to check then I'll merge!

**Comment by Cruisererick** [comment]
Looks good.

**Pull request merged**
